# Redis 8.6.2 配置文件

# 監聽的端口號
port 6379

# 監聽的 IP 地址
#bind 127.0.0.1

# 是否以守護進程模式運行
#daemonize yes

# 以哪個用戶身份運行 Redis 服務
user redis

# 密碼設置，設置密碼後需使用該密碼才能訪問 Redis 服務
requirepass 123456

# 日誌文件的位置和名稱
#logfile /usr/local/etc/redis/log/redis.log

# 持久化保存數據的方式，這裡使用RDB方式進行持久化，並設置了快照的保存頻率
#save 900 1
#save 300 10
#save 60 10000

# 使用AOF持久化方式時，每秒同步數據到磁盤的次數
# appendonly yes
# appendfsync everysec

# 設置最大連接數和最大客戶端數
#maxclients 10000
#maxmemory 2gb

# 限制內存使用的策略
# maxmemory-policy volatile-lru