#Server setting
server.port=8081

#SQL Server setting
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=chatground; \
  CharacterSet=UTF-8;sslProtocol=TLS;encrypt=false; \
  trustServerCertificate=true
#spring.datasource.username=!!yourUsername!!
spring.datasource.username=ENC(PhnOPKzrkuyjHwKfCdKp+Exj69scUs9nUhd3+SQB36OIU70ona3N3aB3pGPq7fHZ)
#spring.datasource.password=!!yourPassword!!
spring.datasource.password=ENC(Jl/757YgzRMhTtyuTAppsnoUN6LDivuJOg4K7jeaEoLv38oyV5uQRIW53y1IW6/b)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.hbm2ddl.auto=update

#顯示sql statement
spring.jpa.show-sql=false
#logging.level.org.hibernate.SQL=DEBUG

#MySQL setting
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/chatground_v2?\
#  useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
#spring.datasource.username=root
#spring.datasource.password=0000
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql=false

#顯示SQL 統計
#spring.jpa.properties.hibernate.generate_statistics=true
#jpa Batch Insert
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true


#i18n 設定
spring.messages.basename=i18n/language
spring.messages.encoding=UTF-8
#expired in 1 hour
spring.messages.cache-duration=3600


#Redis setting

#Redis 資料庫索引(預設為0)
spring.data.redis.database=0
#Redis 伺服器位址
spring.data.redis.host=127.0.0.1
#Redis server port
spring.data.redis.port=6379
#Redis password
#spring.data.redis.password=!!yourRedisPassword!!
spring.data.redis.password=ENC(UNb0p6M+kpPD/89464oieWZJ+C8ZF0jDTE6Ji9Fve4nPywD7ndykhdrRraWw006M)
#連線池最大連結數(使用負值表示沒有限制)
spring.redis.lettuce.pool.max-active=8
#連線池最大阻塞等待時間(使用負值表示沒有限制)
spring.redis.lettuce.pool.max-wait=-1
#連線池最大閒置連線數
spring.redis.lettuce.pool.max-idle=8
#連線池最小閒置連線數
spring.redis.lettuce.pool.min-idle=0
#連線逾時(ms)
spring.data.redis.timeout=5000

#Thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
#為便於測試，在開發時需要關閉快取
spring.thymeleaf.cache=false
#加入view的根路徑
spring.thymeleaf.prefix=classpath:/templates/
#加入static靜態資源的路徑
#spring.web.resources.static-locations=classpath:/static/
#關閉資源的快取
spring.web.resources.cache.period=0

#SLF4J 配置Logging 屬性--不使用，改用logback-spring.xml配置
# 指定Log 檔案位置，不指定路徑則預設在當前專案下生成檔案
#logging.file.path=./log
# 設定Log 檔案名稱，預設為spring.log，使用該配置會覆蓋path 位置，直接在當前專案下生成檔案
#logging.file.name=ChatGroundLog.log
# 指定自定義 logger 物件日誌級別
#logging.level.com.codewhite=INFO

#自訂WebSecurity的debug開關
web.security.security-debug=false

#jasypt加解密金鑰，prod環境要設置在cmd啟動參數中，不儲存在properties。
#jasypt.encryptor.password=!!yourEncryptKey!!
jasypt.encryptor.password=encryptKey